version: "3.0"

services:
  mssql:
    user: root
    image: mcr.microsoft.com/mssql/server:latest
    ports:
      - "1433:1433"
    volumes:
      - ./data/db:/var/opt/mssql/data
      - ./data/log:/var/opt/mssql/log
      - ./data/secrets:/var/opt/mssql/secrets
    environment:
      MSSQL_SA_PASSWORD: 'hL9DpW4MGZ!VgUz'
      ACCEPT_EULA: 'Y'